#pragma once

#define SET_TOTAL_CONSUMPTION			"totalConsumption"
#define SET_TEMP						"setTemp"
#define SET_IS_AUTO 					"setIsAuto"
#define SET_IS_ON						"setIsOn"
#define SET_PRIORITY					"setPriority"
#define SET_TARGET_TEMPERATURE			"setTargetTemp"
#define SET_CONSUMPTION_LIMIT			"setConsumptionLimit"
#define SET_HYSTERESIS					"setHysteresis"
#define SET_SENSOR						"setSensor"
#define SET_PORT						"setPort"
#define SET_TEMPERATURE_ADJUST			"setTempAdjust"
#define SET_CONSUMPTION		    		"setConsumption"
#define SET_IS_ENABLED					"setIsEnabled"
#define EEPROM_ERROR_ITEM				"eepromError"
#define TEMPERATURE_READ_ERROR_ITEM		"tempReadError"

#define ON                              "ON"
#define OFF                             "OFF"