#pragma once

#define SET_TOTAL_CONSUMPTION			"total_consumption"
#define SET_TEMP						"temp"
#define SET_IS_AUTO 					"isauto"
#define SET_IS_ON						"ison"
#define SET_PRIORITY					"priority"
#define SET_TARGET_TEMPERATURE			"targettemp"
#define SET_CONSUMPTION_LIMIT			"consumption_limit"
#define SET_HYSTERESIS					"hysteresis"
#define SET_SENSOR						"sensor"
#define SET_PORT						"port"
#define SET_TEMPERATURE_ADJUST			"tempadjust"
#define SET_CONSUMPTION		    		"consumption"
#define SET_IS_ENABLED					"isenabled"
#define EEPROM_ERROR_ITEM				"eeprom_error"
#define TEMPERATURE_READ_ERROR_ITEM		"temp_read_error"