#pragma once

#define TOTAL_CONSUMPTION			"totalConsumption"
#define TEMPERATURE					"temperature"
#define IS_AUTO 					"isAuto"
#define IS_ON						"isOn"
#define ACTUAL_STATE                "actualState"
#define PRIORITY					"priority"
#define TARGET_TEMPERATURE			"targetTemperature"
#define CONSUMPTION_LIMIT			"consumptionLimit"
#define HYSTERESIS					"hysteresis"
#define SENSOR						"sensor"
#define PORT						"port"
#define TEMPERATURE_ADJUST			"temperatureAdjust"
#define AUX_ADJUST                  "auxAdjust"
#define CONSUMPTION		    		"consumption"
#define IS_ENABLED					"isEnabled"
#define PHASE                       "phase"
#define EEPROM_ERROR_ITEM				"eepromError"
#define TEMPERATURE_READ_ERRORS		"tempReadErrors"

#define ON                              "ON"
#define OFF                             "OFF"